// SIGN IN
export const SIGNIN_REQUEST = "SIGNIN_SUCCESS";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

// SIGN OUT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
